### ISSUE TITLE
svg with colors set via css variables

### ISSUE THREAD

**Issue by cherepanov** [jonathanlermitage/IconViewer#3]
There is no way to view svg with colors set via css variables. Example below.
SVG preview based on TwelveMonkeys lib where i no way to accomplish this.
So the only way to fix this is to process file content before passing to rendering engine.

I see two possible solutions:

1) provide settings ui, where mappings could be set. this leads to big changes .
2) simply replace ```var(--c-blue)``` with currentColor. this should be enough for preview.

```
<svg width='24' height='24' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'>
    <path
        fill-rule='evenodd'
        clip-rule='evenodd'
        d='M16.294 9.29292L13.0011 12.5858V2.00003H11.0011V12.5858L7.70825 9.29292L6.29403 10.7071L12.0011 16.4142L17.7082 10.7071L16.294 9.29292ZM22.001 20V16H20.001V20H4.00098V16H2.00098V20C2.00098 21.1046 2.89641 22 4.00098 22H20.001C21.1055 22 22.001 21.1046 22.001 20Z'
        fill='var(--c-blue)'
    />
</svg>
```

**Comment by cherepanov** [comment]
i made dirty implementations, seems to work. sorry for my bad java:)

**Comment by jonathanlermitage** [comment]
@cherepanov Don't worry, your code is ok :+1:
CSS colors are not displayed because they should be declared in a CSS file. It works with HTML webpages in web browsers, but it cannot work with SVG editors/viewers. I believe this is expected behavior, even if it's super weird: that means we can create SVG files that work correctly in web browsers only 💩.  

Do you know if some SVG editors or viewers can render these CSS colors? (I am using Inkscape and CSS variables are simply ignored)  
I am wondering if `--c-blue` is a standard HTML [color name,](https://www.w3schools.com/colors/colors_names.asp), or a user-defined variable. If it's a variable, we can do nothing.

**Comment by cherepanov** [comment]
Right, these color defined in my project as part of ui theme.  Where is no direct way teach rendered to use them. We process images after editing. Seeing blanks is really annoying.

**Comment by cherepanov** [comment]
The next thing would be to fix preview pane. Can you give me glue which api used there?

**Comment by jonathanlermitage** [comment]
I think you can remove the `fill='none'` from the first line in the SVG file, that's why you see a blank image.

**Comment by cherepanov** [comment]
This may break some images. Better example, currently only fill='white' handled

```
<svg width='40' height='40' viewBox='0 0 40 40' xmlns='http://www.w3.org/2000/svg'>
    <rect
        x='6'
        y='4'
        width='28'
        height='32'
        rx='1'
        fill='white'
        stroke='var(--c-blue)'
        stroke-width='2'
        stroke-linecap='round'
        stroke-linejoin='round'
    />
    <path
        d='M6 4.56522C6 4.25306 6.25306 4 6.56522 4H33.4348C33.7469 4 34 4.25306 34 4.56522C34 9.7759 29.7759 14 24.5652 14H15.4348C10.2241 14 6 9.7759 6 4.56522Z'
        fill='white'
        stroke='var(--c-blue)'
        stroke-width='2'
        stroke-linecap='round'
        stroke-linejoin='round'
    />
    <rect
        x='0.5'
        y='-0.5'
        width='15'
        height='1'
        rx='0.5'
        transform='matrix(1 0 0 -1 12 9)'
        fill='white'
        stroke='var(--c-blue)'
        stroke-linecap='round'
        stroke-linejoin='round'
    />
    <rect
        x='0.5'
        y='-0.5'
        width='6'
        height='1'
        transform='matrix(1 0 0 -1 23 25)'
        fill='white'
        stroke='var(--c-blue)'
        stroke-linecap='round'
        stroke-linejoin='round'
    />
    <rect
        x='0.5'
        y='-0.5'
        width='6'
        height='1'
        transform='matrix(1 0 0 -1 23 21)'
        fill='white'
        stroke='var(--c-blue)'
        stroke-linecap='round'
        stroke-linejoin='round'
    />
    <rect
        x='0.5'
        y='-0.5'
        width='6'
        height='1'
        transform='matrix(1 0 0 -1 23 29)'
        fill='white'
        stroke='var(--c-blue)'
        stroke-linecap='round'
        stroke-linejoin='round'
    />
</svg>
```

**Comment by jonathanlermitage** [comment]
The first image should not contain `fill='none` because it contains a single `path`, and its fill rule `fill='var(--c-blue)'` is ignored, so the `fill='none` rule is applied. That's why I think this is a problem with the SVG image itself. Without the `fill='none`, the path is black colored, we can see something. This is not optimal, but we can do nothing for external CSS rules.  
Same thing for the second image: we can't handle the `var(--c-blue)` rules.  

We could probably add an option to replace all CSS rules by a custom color (black if IntelliJ is using a light theme, white for a dark theme, something like that, we could also let the user pick a color).

**Comment by cherepanov** [comment]
Perfect solution would be to handle colors as they handled in css-files. I have default theme predefined in project-level css, and everything displayed and cross-linked correctly. Probably for some tricky cases we need UI to manually specify colors or point to css-file contains them.

In context of web development having svg's with variables pretty common and valid approach.

My proposition is very simple workaround to display meaningful content without overcomplicating code of this plugin.

Just checked currentColor is mapped to black, for "High Contrast" theme it becomes invisible. With Light and Darkula looks fine. So we need color-shift function depended on current background. Have no idea how to pick it up.

**Comment by jonathanlermitage** [comment]
Oh yeah, sorry, I just realized that `currentColor` is an SVG keyword 🤣 
This is an excellent workaround, for sure. I will validate your pull-request asap.

**Comment by jonathanlermitage** [comment]
PR merged. Thx for your contribution!  
I will probably publish a new release next week.
